# yaml-language-server: $schema=https://raw.githubusercontent.com/srikanthccv/otelcol-jsonschema/main/schema.json

receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

exporters:
  logging:
    logLevel: logging

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      exporters: [logging]